# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ct.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x43t.proto\"8\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04town\x18\x02 \x01(\t\x12\x0f\n\x07postode\x18\x03 \x01(\t\"\xce\x01\n\x06Person\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x64ob\x18\x03 \x01(\t\x12\x19\n\x07\x61\x64\x64ress\x18\x04 \x01(\x0b\x32\x08.Address\x12\x11\n\ttelephone\x18\x05 \x01(\t\x12\x0c\n\x04pets\x18\x06 \x03(\t\x12\r\n\x05score\x18\x07 \x01(\x02\x12\r\n\x05\x65mail\x18\x08 \x01(\t\x12\x0b\n\x03url\x18\t \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12\x10\n\x08verified\x18\x0b \x01(\x08\x12\x0e\n\x06salary\x18\x0c \x01(\x05\"!\n\x06\x43tRoot\x12\x17\n\x06\x63tRoot\x18\x01 \x03(\x0b\x32\x07.Personb\x06proto3')



_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_PERSON = DESCRIPTOR.message_types_by_name['Person']
_CTROOT = DESCRIPTOR.message_types_by_name['CtRoot']
Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'Ct_pb2'
  # @@protoc_insertion_point(class_scope:Address)
  })
_sym_db.RegisterMessage(Address)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'Ct_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  })
_sym_db.RegisterMessage(Person)

CtRoot = _reflection.GeneratedProtocolMessageType('CtRoot', (_message.Message,), {
  'DESCRIPTOR' : _CTROOT,
  '__module__' : 'Ct_pb2'
  # @@protoc_insertion_point(class_scope:CtRoot)
  })
_sym_db.RegisterMessage(CtRoot)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESS._serialized_start=12
  _ADDRESS._serialized_end=68
  _PERSON._serialized_start=71
  _PERSON._serialized_end=277
  _CTROOT._serialized_start=279
  _CTROOT._serialized_end=312
# @@protoc_insertion_point(module_scope)
